/* eslint-disable react-refresh/only-export-components -- provider module intentionally exports its typed hook */
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, CheckCircle2, Info, X, XCircle } from "lucide-react";
export type ToastType = "success" | "error" | "warning" | "info";
export interface ToastAction { label: string; onClick: () => void }
export interface ToastProps { id?: string; message: string; type?: ToastType; duration?: number; action?: ToastAction; onDismiss?: () => void }
const styles = { success: "border-emerald-500/30 bg-emerald-950 text-emerald-100", error: "border-red-500/30 bg-red-950 text-red-100", warning: "border-amber-500/30 bg-amber-950 text-amber-100", info: "border-indigo-500/30 bg-indigo-950 text-indigo-100" } as const;
const icons = { success: CheckCircle2, error: XCircle, warning: AlertTriangle, info: Info } as const;
export function Toast({ message, type = "info", duration = 5000, action, onDismiss }: ToastProps) { const Icon = icons[type]; useEffect(() => { if (duration <= 0) return; const timer = window.setTimeout(() => onDismiss?.(), duration); return () => window.clearTimeout(timer); }, [duration, onDismiss]); return <div role={type === "error" ? "alert" : "status"} className={`flex w-full items-start gap-3 rounded-lg border p-4 shadow-lg shadow-black/30 ${styles[type]}`}><Icon className="mt-0.5 shrink-0" size={19} /><p className="flex-1 text-sm">{message}</p>{action && <button onClick={action.onClick} className="text-sm font-semibold underline underline-offset-2">{action.label}</button>}<button aria-label="Chiudi notifica" onClick={onDismiss} className="rounded p-0.5 opacity-70 hover:opacity-100"><X size={16} /></button></div>; }
interface ToastItem extends Required<Pick<ToastProps, "id" | "message" | "type" | "duration">> { action?: ToastAction }
interface ToastContextValue { toasts: ToastItem[]; showToast: (toast: Omit<ToastProps, "id" | "onDismiss">) => string; dismissToast: (id: string) => void }
const ToastContext = createContext<ToastContextValue | undefined>(undefined);
export function ToastProvider({ children }: { children: ReactNode }) { const [toasts, setToasts] = useState<ToastItem[]>([]); const dismissToast = useCallback((id: string) => setToasts((items) => items.filter((item) => item.id !== id)), []); const showToast = useCallback((toast: Omit<ToastProps, "id" | "onDismiss">): string => { const id = crypto.randomUUID(); setToasts((items) => [...items, { id, message: toast.message, type: toast.type ?? "info", duration: toast.duration ?? 5000, action: toast.action }]); return id; }, []); const value = useMemo(() => ({ toasts, showToast, dismissToast }), [dismissToast, showToast, toasts]); return <ToastContext.Provider value={value}>{children}<div aria-live="polite" aria-relevant="additions" className="pointer-events-none fixed right-4 top-4 z-[100] flex w-[calc(100%-2rem)] max-w-sm flex-col gap-2">{toasts.map((toast) => <div key={toast.id} className="pointer-events-auto"><Toast {...toast} onDismiss={() => dismissToast(toast.id)} /></div>)}</div></ToastContext.Provider>; }
export function useToasts(): ToastContextValue { const context = useContext(ToastContext); if (!context) throw new Error("useToasts must be used within ToastProvider"); return context; }
