import { type ButtonHTMLAttributes, type ReactNode, useMemo, useState } from "react";
import { AlertCircle, Box, ChevronLeft, ChevronRight, LoaderCircle, PackageOpen, X } from "lucide-react";
import ProductImage from "./ProductImage";
import { categoryName, type Order, type OrderStatus, type Product } from "../types";

type ButtonVariant = "primary" | "secondary" | "danger" | "ghost";
type ButtonSize = "sm" | "md" | "lg";
interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: ButtonVariant; size?: ButtonSize; loading?: boolean; icon?: ReactNode }
const buttonVariants: Record<ButtonVariant, string> = { primary: "bg-indigo-600 text-white hover:bg-indigo-500", secondary: "border border-slate-700 bg-slate-800 text-slate-100 hover:border-indigo-500", danger: "bg-red-500 text-white hover:bg-red-400", ghost: "text-slate-300 hover:bg-slate-800" };
const buttonSizes: Record<ButtonSize, string> = { sm: "px-3 py-1.5 text-xs", md: "px-4 py-2 text-sm", lg: "px-5 py-3 text-base" };
export function Button({ variant = "primary", size = "md", loading = false, icon, children, disabled, className = "", ...props }: ButtonProps) { return <button disabled={disabled || loading} className={`inline-flex items-center justify-center gap-2 rounded-lg font-semibold transition-all duration-200 disabled:cursor-not-allowed disabled:opacity-50 ${buttonVariants[variant]} ${buttonSizes[size]} ${className}`} {...props}>{loading ? <LoaderCircle className="animate-spin" size={16} /> : icon}{children}</button>; }

interface CardProps { children: ReactNode; elevation?: "none" | "sm" | "lg"; interactive?: boolean; className?: string }
export function Card({ children, elevation = "sm", interactive = false, className = "" }: CardProps) { const shadows = { none: "", sm: "shadow-sm", lg: "shadow-xl shadow-black/20" }; return <div className={`rounded-2xl border border-slate-700/80 bg-slate-900/80 ${shadows[elevation]} ${interactive ? "transition-all duration-300 hover:-translate-y-0.5 hover:border-indigo-500/70 hover:shadow-xl hover:shadow-indigo-950/30" : ""} ${className}`}>{children}</div>; }

const badgeStyles: Record<OrderStatus, string> = { pending: "border-amber-500/30 bg-amber-500/10 text-amber-400", processing: "border-cyan-500/30 bg-cyan-500/10 text-cyan-400", shipped: "border-blue-500/30 bg-blue-500/10 text-blue-400", delivered: "border-emerald-500/30 bg-emerald-500/10 text-emerald-400", completed: "border-emerald-500/30 bg-emerald-500/10 text-emerald-400", cancelled: "border-red-500/30 bg-red-500/10 text-red-400" };
export function Badge({ status }: { status: OrderStatus }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold capitalize ${badgeStyles[status]}`}>{status}</span>; }

interface ModalProps { open: boolean; title: string; children: ReactNode; onClose: () => void; footer?: ReactNode }
export function Modal({ open, title, children, onClose, footer }: ModalProps) { if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center p-4"><button aria-label="Close modal" className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm" onClick={onClose} /><Card elevation="lg" className="relative z-10 w-full max-w-lg"><header className="flex items-center justify-between border-b border-slate-700 p-5"><h2 className="font-bold">{title}</h2><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white"><X size={18} /></button></header><div className="p-5">{children}</div>{footer && <footer className="border-t border-slate-700 p-5">{footer}</footer>}</Card></div>; }

export interface TableColumn<T> { key: string; header: string; render: (row: T) => ReactNode; sortValue?: (row: T) => string | number }
interface TableProps<T> { rows: T[]; columns: TableColumn<T>[]; rowKey: (row: T) => string; pageSize?: number }
export function Table<T>({ rows, columns, rowKey, pageSize = 8 }: TableProps<T>) { const [page, setPage] = useState<number>(0); const [sortKey, setSortKey] = useState<string>(""); const [ascending, setAscending] = useState<boolean>(true); const sorted = useMemo(() => { const column = columns.find((item) => item.key === sortKey); if (!column?.sortValue) return rows; return [...rows].sort((a, b) => String(column.sortValue?.(a) ?? "").localeCompare(String(column.sortValue?.(b) ?? ""), undefined, { numeric: true }) * (ascending ? 1 : -1)); }, [ascending, columns, rows, sortKey]); const pages = Math.max(1, Math.ceil(rows.length / pageSize)); const visible = sorted.slice(page * pageSize, (page + 1) * pageSize); return <div className="overflow-hidden rounded-xl border border-slate-700"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-700"><thead className="bg-slate-800/80"><tr>{columns.map((column) => <th key={column.key} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-400"><button disabled={!column.sortValue} onClick={() => { setSortKey(column.key); setAscending(sortKey === column.key ? !ascending : true); }}>{column.header}</button></th>)}</tr></thead><tbody className="divide-y divide-slate-800">{visible.map((row) => <tr key={rowKey(row)} className="transition-colors duration-200 hover:bg-slate-800/50">{columns.map((column) => <td key={column.key} className="whitespace-nowrap px-4 py-3 text-sm">{column.render(row)}</td>)}</tr>)}</tbody></table></div><footer className="flex items-center justify-between border-t border-slate-700 px-4 py-3 text-xs text-slate-400"><span>Pagina {page + 1} di {pages}</span><div className="flex gap-2"><button disabled={page === 0} onClick={() => setPage((value) => value - 1)}><ChevronLeft /></button><button disabled={page + 1 >= pages} onClick={() => setPage((value) => value + 1)}><ChevronRight /></button></div></footer></div>; }

interface StatsCardProps { label: string; value: string; trend?: string; icon: ReactNode; color?: "indigo" | "emerald" | "amber" | "red" }
export function StatsCard({ label, value, trend, icon, color = "indigo" }: StatsCardProps) { const colors = { indigo: "bg-indigo-500/15 text-indigo-400", emerald: "bg-emerald-500/15 text-emerald-400", amber: "bg-amber-500/15 text-amber-400", red: "bg-red-500/15 text-red-400" }; return <Card interactive className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{trend && <p className="mt-2 text-xs text-emerald-400">{trend}</p>}</div><span className={`rounded-xl p-3 ${colors[color]}`}>{icon}</span></div></Card>; }

export function ProductCard({ product, action }: { product: Product; action?: ReactNode }) { return <Card interactive className="overflow-hidden"><ProductImage src={product.image} alt={product.name} className="aspect-[4/3] rounded-none border-0" /><div className="p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{product.name}</p><p className="text-xs text-slate-400">{categoryName(product.category)}</p></div><p className="font-bold text-indigo-400">${product.price.toFixed(2)}</p></div><div className="mt-4 flex items-center justify-between"><span className={product.stock < 5 ? "text-xs text-amber-400" : "text-xs text-emerald-400"}>{product.stock} in stock</span>{action}</div></div></Card>; }
export function OrderCard({ order }: { order: Order }) { return <Card interactive className="p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">#{order._id.slice(-8).toUpperCase()}</p><p className="text-xs text-slate-400">{new Date(order.createdAt).toLocaleDateString()}</p></div><Badge status={order.status} /></div><p className="mt-4 text-lg font-bold">${order.totalPrice.toFixed(2)}</p></Card>; }
export function LoadingSpinner({ label = "Caricamento..." }: { label?: string }) { return <div className="flex items-center justify-center gap-2 p-8 text-sm text-slate-400"><LoaderCircle className="animate-spin text-indigo-500" />{label}</div>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="grid place-items-center p-10 text-center"><PackageOpen className="text-slate-600" size={38} /><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-sm text-slate-400">{description}</p></div>; }
export function ErrorMessage({ message }: { message: string }) { return <div className="flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-400"><AlertCircle size={18} />{message}</div>; }
export function InventoryIcon() { return <Box size={20} />; }
