import { useCallback, useMemo } from "react";
import api from "../../api/axios";
import type { ApiEnvelope, Product, ProductInput } from "../../types";
import { invalidateCache } from "./cache";
import { useMutation } from "./useMutation";
import { useQuery } from "./useQuery";

const unwrapProducts = (payload: Product[] | ApiEnvelope<Product[]>): { products: Product[]; total: number } => Array.isArray(payload) ? { products: payload, total: payload.length } : { products: payload.data, total: payload.pagination?.total ?? payload.data.length };
export function useProducts(category?: string, page = 1) { const key = `products:list:${category ?? "all"}:${page}`; const fetcher = useCallback(async () => { const { data } = await api.get<Product[] | ApiEnvelope<Product[]>>("/products", { params: { category, page } }); return unwrapProducts(data); }, [category, page]); const query = useQuery(key, fetcher, { refreshInterval: 60_000 }); return { products: query.data?.products ?? [], total: query.data?.total ?? 0, page, loading: query.loading, error: query.error, refetch: query.refetch }; }
export function useProduct(id: string) { const fetcher = useCallback(async () => { const { data } = await api.get<ApiEnvelope<Product> | Product>(`/products/${id}`); return "data" in data ? data.data : data; }, [id]); const query = useQuery(`products:item:${id}`, fetcher, { enabled: Boolean(id) }); return { product: query.data, loading: query.loading, error: query.error, refetch: query.refetch }; }

const toFormData = (input: ProductInput): FormData => { const form = new FormData(); form.append("name", input.name); form.append("description", input.description); form.append("price", String(input.price)); form.append("stock", String(input.stock)); form.append("category", input.category); form.append("sku", input.sku); if (input.image instanceof File) form.append("image", input.image); else if (input.image) form.append("image", input.image); if (input.imageUrl) form.append("imageUrl", input.imageUrl); return form; };
export function useCreateProduct() { const mutation = useCallback(async (input: ProductInput): Promise<Product> => { const { data } = await api.post<Product>("/products", toFormData(input)); invalidateCache("products:"); return data; }, []); const result = useMutation(mutation); return { ...result, mutate: result.mutate }; }
export function useUpdateProduct(id: string) { const mutation = useCallback(async (input: Partial<ProductInput>): Promise<Product> => { const { data } = await api.put<Product>(`/products/${id}`, input); invalidateCache("products:"); return data; }, [id]); return useMutation(mutation); }
export function useDeleteProduct(id: string) { const mutation = useCallback(async (): Promise<void> => { await api.delete(`/products/${id}`); invalidateCache("products:"); }, [id]); const { mutate, loading, error } = useMutation<void, void>(mutation); return useMemo(() => ({ mutate: () => mutate(undefined), loading, error }), [error, loading, mutate]); }
export function useLowStockProducts() { const fetcher = useCallback(async () => { const { data } = await api.get<ApiEnvelope<Product[]> | Product[]>("/products/low-stock"); return unwrapProducts(data).products; }, []); const query = useQuery("products:low-stock", fetcher, { refreshInterval: 45_000 }); return { products: query.data ?? [], loading: query.loading, error: query.error, refetch: query.refetch }; }
